### ISSUE TITLE
Request to use some code from Partdump

### ISSUE THREAD

**Issue by ghost** [jschicht/PartDump#1]
Hi Joakim,

I am the author of Grub2Win, a software used to multi boot Windows and Linux systems. Grub2Win is written in AutoIt.

I would like to use several of your routines from PartDump to retrieve the properties of non-NTFS partitions.

I hope you will allow me to use your code. I will give you credit both in the release notes and the credits section of the Grub2Win help file.

Please let me know.

Thanks,

Dave

**Comment by jschicht** [comment]
Go ahead and use it. Let me know if you run into any bugs with it.
